"""add_total_amount_to_reservations

Revision ID: d1f7678e62b6
Revises: be4d53acdf5d
Create Date: 2025-07-17 17:34:23.277914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f7678e62b6'
down_revision: Union[str, None] = 'be4d53acdf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_amount')
    # ### end Alembic commands ###
